services:
  webserver-apache2:
    image: surajbele/batch19:apache2
    ports:
      - 80:80
    volumes:
      - /var/lib/docker/volumes/data:/var/www/html
  tomcat-sever:
    image: apache/tomcat:9.0
    ports:
      - 8080:8080
    environment:
       department: "DevOps"
  database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin123
