- name: "my first ansible playbook"
  hosts: all
  vars: 
    name: "Jay"
  tasks:
    - name: "print hello world"
      debug:
        msg: "Hello Ansible"
    - name: "print custom message"
      debug:
        msg: "This is my first Ansible playbook"
    - name: "print variable message"
      debug:
        msg: "Welcome {{name}} to Ansible"
    - name: register value example
      shell: hostname
      register: myhostvalue
    - name: print hostname value from register
      debug:
         msg: "{{myhostvalue.stdout}}"